// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const INCREMENT_FRIENDS_COUNT = 'INCREMENT_FRIENDS_COUNT'
export const DECREMENT_FRIENDS_COUNT = 'DECREMENT_FRIENDS_COUNT'
export const DECREMENT_FRIEND_REQUESTS_COUNT = 'DECREMENT_FRIEND_REQUESTS_COUNT'
